### ISSUE TITLE
Doesn't seem to work on Vercel + how does this actually work?

### ISSUE THREAD

**Issue by Vadorequest** [flawyte/static-auth#3]
Hi, thanks for this lib.

I tried implementing it at https://github.com/UnlyEd/next-right-now/pull/222/files but it doesn't seem to work.

Also, I don't understand how this is supposed to work. What uses the `index.tsx` file? I can't make sense of what happens in the background. 🤔 

Is it compatible with ES7/TS or should it be written the same way as you code examples? (using `require` etc.)

Will it work locally? I guess not since Vercel isn't simulated locally.

**Comment by Vadorequest** [comment]
Eventually figured the index.js acts as a middleware and all routes are configured to go through it from vercel.json.

https://github.com/flawyte/vercel-basic-auth/blob/master/node-static-auth/vercel.json

**Comment by Vadorequest** [comment]
I suggest you update the readme and add an actual step 3, looks like it's actually needed. 😄

**Comment by Vadorequest** [comment]
Maybe what I'm trying to do isn't meant to work, because I use a Serverless build, not a static build. It just occurred to me.

**Comment by flawyte** [comment]
Hi,

>Also, I don't understand how this is supposed to work. What uses the index.tsx file? I can't make sense of what happens in the background. 🤔
>
>Is it compatible with ES7/TS or should it be written the same way as you code examples? (using require etc.)

The `index.ts` file is the lib's entrypoint. It's not meant to be imported directly, but if your project is in TypeScript maybe you can import it directly, I haven't tried. However the standard way to import this lib in your project is to `require()` or `import` one of the files in the library's `dist/` directory (see [file list][1]). In your case I think the `static-auth.modern.js` build variant is the most suited one.

[1]: https://unpkg.com/browse/static-auth@2.0.0/dist/

> Will it work locally? I guess not since Vercel isn't simulated locally.

Yes it works locally. For example if you're building a static website and use `vercel dev` to run it and the package is set up correctly, you'll get the basic auth prompt upon first visit.

> Eventually figured the index.js acts as a middleware and all routes are configured to go through it from vercel.json.

Exactly! You're right about the fact that the README doesn't really explain how the package works under-the-hood, but only how to use it. I'll add some clarifications!

> Maybe what I'm trying to do isn't meant to work, because I use a Serverless build, not a static build. It just occurred to me.

Yep that could the problem in your case, because this package has originally been designed to add a basic auth layer over **static files** (or an entire website made of static files). If you want to add basic auth to SSR or API routes, this won't work because `static-auth` can only serve files. In this case you'll have to do it manually or use another package.

**Comment by hormesiel** [comment]
Hi,

>Also, I don't understand how this is supposed to work. What uses the index.tsx file? I can't make sense of what happens in the background. 🤔
>
>Is it compatible with ES7/TS or should it be written the same way as you code examples? (using require etc.)

The `index.ts` file is the lib's entrypoint. It's not meant to be imported directly, but if your project is in TypeScript maybe you can import it directly, I haven't tried. However the standard way to import this lib in your project is to `require()` or `import` one of the files in the library's `dist/` directory (see [file list][1]). In your case I think the `static-auth.modern.js` build variant is the most suited one.

[1]: https://unpkg.com/browse/static-auth@latest/dist/

> Will it work locally? I guess not since Vercel isn't simulated locally.

Yes it works locally. For example if you're building a static website and use `vercel dev` to run it and the package is set up correctly, you'll get the basic auth prompt upon first visit.

> Eventually figured the index.js acts as a middleware and all routes are configured to go through it from vercel.json.

Exactly! You're right about the fact that the README doesn't really explain how the package works under-the-hood, but only how to use it. I'll add some clarifications!

> Maybe what I'm trying to do isn't meant to work, because I use a Serverless build, not a static build. It just occurred to me.

Yep that could be the problem in your case, because this package has been designed to add a basic auth layer over **static files** (or pages made of static files), hence the name : *__static__-auth*. If you want to add basic auth to SSR or API routes, this won't work because `static-auth` can only serve files. In this case you'll have to do it manually or use another package.

**Comment by Vadorequest** [comment]
Thanks for the feedback! I think you should clarify that static-auth only works with Next.js "Export" mode (exporting a site as a bunch of static pages), not "serverless" mode. Because people might think (as I did) it would work when using SSG instead of SSR, but it doesn't.

**Comment by hormesiel** [comment]
Yep I'll add a reminder that it works with static files only. Note, though, that the readme never mentions Next.js since it hasn't been made specifically for this framework.
